config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/showroom", to: "pages#showroom"
  get "/quienes_somos", to: "pages#quienes_somos"
  get "/politica_de_cambio", to: "pages#politica_de_cambio"
  get "/talleres", to: "pages#talleres"
  get "/eventos", to: "pages#eventos"
  get "/tienda", to: "pages#tienda"
  get "/dashboard", to: "pages#dashboard"
  get "/product", to: "pages#product"

  resources :workshops, only: [:new, :create, :show, :destroy]
  resources :contacts, only: [:create]
  resources :events, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :items, only: [:new, :create, :destroy]
  resources :billboards, only: [:new, :create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% agent = request.user_agent %>
<% if agent =~ /Mobile/ %>
  <div class="navbar-mobile">
    <i class="fa-solid fa-bars menu-mobile" data-action="click->slide#display"></i>
    <%= link_to root_path do %>
      <img src="https://d3ugyf2ht6aenh.cloudfront.net/stores/001/206/817/themes/common/logo-238479029-1681492343-1a7bfbbe807402a2c472c0ab13882f851681492343-480-0.png?0" class="logo-mobile">
      <%# <%= image_tag "logo.png", class: "logo-mobile" %>
    <% end %>
    <%# <%= link_to "https://brindisespumante.com.ar/checkout" do %>
      <%# <%= image_tag "Icono_Carrito.png", class: "carrito"
    <%# <% end %>
    <div></div>
  </div>


  <div class="side-menu-mobile" data-slide-target="menu">
    <a href="<%= root_path %>" class="side-inicio" id="remove_underline">
      <%= image_tag "dibujos_maggie/calles/calles_pag_web_copy-01.png", id: "slide-img" %>
      <p id="inicio" style="font-family: 'Roboto', sans-serif;">Inicio</p>
    </a>
    <a href="<%= tienda_path %>"class="side-inicio" id="remove_underline">
      <%= image_tag "inicio/Tienda.png", id: "slide-img" %>
      <p id="inicio" style="font-family: 'Roboto', sans-serif;">Productos</p>
    </a>
    <a href="<%= quienes_somos_path %>" class="side-inicio" id="remove_underline">
      <%= image_tag "quienes_somos/quienes_somos_pagina.png", id: "slide-img" %>
      <p id="inicio" style="font-family: 'Roboto', sans-serif;">Quienes Somos</p>
    </a>
    <a href="<%= showroom_path %>" class="side-inicio" id="remove_underline">
      <%= image_tag "showroom.png", id: "slide-img" %>
      <p id="inicio" style="font-family: 'Roboto', sans-serif;">Contacto</p>
    </a>
    <a href="<%= eventos_path %>" class="side-inicio" id="remove_underline">
      <%= image_tag "inicio/Eventos.png", id: "slide-img" %>
      <p id="inicio" style="font-family: 'Roboto', sans-serif;">Eventos</p>
    </a>
    <a href="<%= talleres_path %>" class="side-inicio" id="remove_underline">
      <%= image_tag "inicio/Talleres.png", id: "slide-img" %>
      <p id="inicio" style="font-family: 'Roboto', sans-serif;">Talleres</p>
    </a>
    <a href="<%= politica_de_cambio_path %>" class="side-inicio" id="remove_underline">
      <%= image_tag "inicio/basura.png", id: "slide-img" %>
      <p id="inicio" style="font-family: 'Roboto', sans-serif;">Política de Cambio</p>
    </a>
  </div>


<% else %>
  <div class="navbar">
    <div class="container">
      <%= link_to root_path do %>
      <img src="https://d3ugyf2ht6aenh.cloudfront.net/stores/001/206/817/themes/common/logo-238479029-1681492343-1a7bfbbe807402a2c472c0ab13882f851681492343-480-0.png?0" class="logo">
        <%#= image_tag "logo.png", class: "logo" %>
      <% end %>

      <div class="navbar-flex" id="non-serif">
        <%= link_to "Admin", dashboard_path if user_signed_in? %>
        <%= link_to "Inicio", root_path %>
        <%= link_to "Productos", tienda_path %>
        <%= link_to "Quienes somos", quienes_somos_path %>
        <%= link_to "Contacto", showroom_path %>
        <%= link_to "Preguntas Frecuentes", "https://brindisespumante.com.ar/preguntas-frecuentes/" %>
        <%# <%= link_to "https://brindisespumante.com.ar/checkout" do %>
          <%# <%= image_tag "Icono_Carrito.png", class: "carrito"
        <%# <% end %>
      </div>

    </div>
  </div>
<% end %>

app/views/shared/_whatsapp.html.erb
<% agent = request.user_agent %>
<%= link_to "https://wa.me/5491130824325?text=Hola", target: "_blank" do %>
  <% if agent =~ /Mobile/ %>
      <%= image_tag "logo_wpp.png", id: "wpp-logo" %>
  <% else %>
    <%= image_tag "logo_wpp.png", id: "wpp-logo-desktop" %>
  <% end %>
<% end %>