config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/showroom", to: "pages#showroom"
  get "/quienes_somos", to: "pages#quienes_somos"
  get "/politica_de_cambio", to: "pages#politica_de_cambio"
  get "/talleres", to: "pages#talleres"
  get "/eventos", to: "pages#eventos"
  get "/tienda", to: "pages#tienda"
  get "/dashboard", to: "pages#dashboard"
  get "/product", to: "pages#product"

  resources :workshops, only: [:new, :create, :show, :destroy]
  resources :contacts, only: [:create]
  resources :events, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :items, only: [:new, :create, :destroy]
  resources :billboards, only: [:new, :create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :poster
  has_many_attached :photos
  has_rich_text :description
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    authorize @event

    if @event.save
      redirect_to eventos_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
    authorize @event
  end

  def edit
    @event = Event.find(params[:id])
    authorize @event
  end

  def update
    @event = Event.find(params[:id])
    authorize @event
    if @event.update(event_params)
      redirect_to eventos_path
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    authorize @event

    if @event.destroy
      redirect_to eventos_path
    else
      render :show
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :start_time, :end_time, :poster, photos: [])
  end
end

app/views/events/edit.html.erb
<div class="talleres-new" data-controller="trix">
  <%= simple_form_for @event, html: {class: "edit-form"} do |f| %>
    <h4>Subir fotos de <%= @event.title %></h4>
    <%= f.input :photos, as: :file, label: "Fotos", input_html: { multiple: true } %>
    <%= f.submit "Crear evento" %>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="talleres-new" data-controller="trix">
  <%= simple_form_for @event, html: {class: "new-form"} do |f| %>
    <h4>Crear evento</h4>
    <%= f.input :title, label: "Título" %>
    <%= f.input :description, as: :rich_text_area, label: "Descripción" %>
    <%= f.input :date, label: "Fecha", as: :string, input_html: { data: {controller: "flatpickr"}}  %>
    <%= f.input :start_time, label: "Comienzo" %>
    <%= f.input :end_time, label: "Final" %>
    <%= f.input :poster, as: :file, label: "Poster" %>
    <%= f.submit "Crear evento" %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="event-show">
  <div class="event-show-left">
    <%= cl_image_tag @event.poster.key %>
  </div>

  <div class="event-show-right">
    <h5 id="non-serif"><strong><em><%= @event.title.upcase %></em></strong></h5>
    <p><strong><%= @event.description %></strong></p>
    <br>
    <%= link_to "Borrar evento", event_path(@event), data: {turbo_method: :delete} if user_signed_in? %>
    <p style="text-shadow: none;"><strong>A continuación les dejamos videos y fotos del Evento:</strong></p>
    
    <div class="photos-grid">
      <% @event.photos.take(8).each do |photo| %>
        <%= cl_image_tag photo.key, class: "event-photo" %>
      <% end %>
    </div>
    
    <% if user_signed_in? %>
      <%= link_to "+ Photo", edit_event_path(@event) %>
    <% end %>
  </div>
</div>