config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/showroom", to: "pages#showroom"
  get "/quienes_somos", to: "pages#quienes_somos"
  get "/politica_de_cambio", to: "pages#politica_de_cambio"
  get "/talleres", to: "pages#talleres"
  get "/eventos", to: "pages#eventos"
  get "/tienda", to: "pages#tienda"
  get "/dashboard", to: "pages#dashboard"
  get "/product", to: "pages#product"

  resources :workshops, only: [:new, :create, :show, :destroy]
  resources :contacts, only: [:create]
  resources :events, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :items, only: [:new, :create, :destroy]
  resources :billboards, only: [:new, :create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/dashboard.html.erb
<div class="admin">
  <%= link_to "+ Taller", new_workshop_path %>
  <%= link_to "+ Evento", new_event_path %>
  <%= link_to "Cambiar productos en promoción", new_item_path %>
  <%= link_to "Cambiar texto de cartelera", new_billboard_path %>
  <%= link_to "Cerrar sessión", destroy_user_session_path, data: {turbo_method: :delete} %>
</div>

app/views/pages/eventos.html+phone.erb
<div class="eventos-mobile">
  <% if @events_upcoming.empty? %>
   <h5 style="text-align: center;">Aún no hay eventos. Vuelve pronto! :)</h5>
  <% else %>
    <div class="comming-events">
      <strong><p id="eventos-text">Eventos por venir</p></strong>
      <div data-controller="galleria">
        <section class="slider" style="padding-left: 1rem;">
          <button class="slider__control prev"></button>
          <button class="slider__control next"></button>
          <div class="slider__container" data-multislide="true" data-step="4" style="padding: 2vh 0;">
          <% @events_upcoming.each do |event| %>
            <div class="events-card-container slider__item" style="width: calc(100% / 2); background: transparent; padding: 0; height: auto;">
              <div class="sub-container">
                <div class="events-card-title">
                <strong> <p><%= event.title %></p> </strong>
                <p><%= event.date %></p>
                </div>
                <div class="events-card-subtitle">
                  <p>subtitle</p>
                  <p>TIME</p>
                  <p>little description</p>
                </div>
                <div class="events-card-img">
                  <%= image_tag "talleres/entrada_byn.png", id: "events-img" %>
                </div>
              </div>
              <div class="events-card-desc">
                <p>Día de la primavera y feria</p>
                <p>Showroom b_rindis</p>
              </div>
            </div>
          <% end %>
        </section>
      </div>
    </div>
  <% end %>

  <% unless @events_past.empty? %>
    <div class="past-events">
      <strong><p id="eventos-pasados-text">Eventos Pasados</p></strong>

      <div data-controller="galleria">
        <section class="slider" style="padding-left: 1rem;">
          <button class="slider__control prev"></button>
          <button class="slider__control next"></button>
          <div class="slider__container" data-multislide="true" data-step="4" style="padding: 2vh 0;">
          <% @events_past.each do |event| %>
            <div class="events-card-container slider__item" style="width: calc(100% / 2); background: transparent; padding: 0; height: auto;">
              <div class="sub-container">
                <div class="events-card-title">
                <strong> <p><%= event.title %></p> </strong>
                <p><%= event.date %></p>
                </div>
                <div class="events-card-subtitle">
                  <p>subtitle</p>
                  <p>TIME</p>
                  <p>little description</p>
                </div>
                <div class="events-card-img">
                  <%= image_tag "talleres/entrada_byn.png", id: "events-img" %>
                </div>
              </div>
              <div class="events-card-desc">
                <p>Día de la primavera y feria</p>
                <p>Showroom b_rindis</p>
              </div>
            </div>
          <% end %>
          </section>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/home.html+phone.erb
<div class="home_mobile">
  <% if @billboard_item %>
    <div class="billboard-box-mobile">
      <h5 class="billboard-text-mobile"><%= @billboard_item.text %></h5>
    </div>
  <% end %>
  <%= link_to tienda_path, id: "link-tienda" do %>
  <% end %>
  <%= link_to showroom_path, id: "link-showroom" do %>
  <% end %>
  <%= link_to quienes_somos_path, id: "link-quienes_somos" do %>
  <% end %>
  <%= link_to politica_de_cambio_path, id: "link-quienes_somos" do %>
  <% end %>
  <%= link_to talleres_path, id: "link-talleres" do %>
  <% end %>
  <%= link_to eventos_path, id: "link-eventos" do %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="home-outer">
  <%= image_tag "wetransfer/PNG/decorativos_13.png", class: "lake" %>
  <%= image_tag "inicio/Fondo_Politica_de_cambio_Inicio.png", class: "grass grass-1" %>
  <%= image_tag "inicio/Fondo_Politica_de_cambio_Inicio.png", class: "grass grass-2" %>
  <%= image_tag "inicio/Fondo_Politica_de_cambio_Inicio.png", class: "grass grass-3" %>
  <%= image_tag "inicio/Fondo_Politica_de_cambio_Inicio.png", class: "grass grass-4" %>

  <div class="home3">
    <a href="<%= eventos_path %>" class="building eventos-home">
      <p class="text">Eventos</p>
    </a>

    <a href="<%= tienda_path %>" class="building tienda-home">
      <p class="text">Tienda Brindis</p>
    </a>

    <a href="<%= showroom_path %>" class="building showroom-home">
      <p class="text">Contacto</p>
    </a>

    <a class="building quienes-somos-home" href="<%= quienes_somos_path %>">
      <div>
        <%= image_tag "quienes_somos/quienes_somos_pagina.png" %>
        <p class="text">Quienes Somos</p>
      </div>
    </a>

    <a class="building talleres-home" href="<%= talleres_path %>" >
      <p class="text">Talleres</p>
    </a>

    <a class="building politica-home" href="<%= politica_de_cambio_path %>" >
      <%= image_tag "Icono_Planta.png" %>
      <%= image_tag "inicio/basura.png" %>
      <p class="text">Politica de Cambio</p>
    </a>

    <div class="info-home" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <p id="non-serif">Proyecto B_rindis invita a usar prendas comodas y versátiles. Usar Brindis es vestir con estilo, es aceptarnos y aceptar a todxs. Somos un proyecto familiar que surge como una opción alternativa a la industria de la moda. Apostamos a una producción humana y consciente, realizada en nuestro país y aspiramos al crecimiento de esta sin perder nuestro origen.</p>
    </div>

    <%= image_tag "wetransfer/PNG/cartel_02.png", class: "sign" %>

    <% if @billboard_item %>
      <div class="billboard-box">
        <h5 class="billboard-text"><%= @billboard_item.text %></h5>
      </div>
    <% end %>

    <%= image_tag "wetransfer/PNG/nube_02.png", class: "cloud-1" %>
    <% if @cloud_item_left %>
      <%= link_to @cloud_item_left.link do %>
        <%= cl_image_tag @cloud_item_left.photo.key, class: "item item-1" %>
      <% end %>
    <% else %>
      <%= image_tag "fotos_pagina/remera-rufino.png", class: "item item-1" %>
    <% end %>

    <% if @cloud_item_center %>
      <%= link_to @cloud_item_center.link do %>
        <%= cl_image_tag @cloud_item_center.photo.key, class: "item item-2" %>
      <% end %>
    <% else %>
      <%= image_tag "fotos_pagina/remera-rufino.png", class: "item item-2" %>
    <% end %>

    <%= image_tag "wetransfer/PNG/nube_01.png", class: "cloud-2" %>

    <% if @cloud_item_right %>
      <%= link_to @cloud_item_right.link do %>
        <%= cl_image_tag @cloud_item_right.photo.key, class: "item item-3" %>
      <% end %>
    <% else %>
      <%= image_tag "fotos_pagina/remera-rufino.png", class: "item item-3" %>
    <% end %>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <div>
      <img src="https://d3ugyf2ht6aenh.cloudfront.net/stores/001/206/817/themes/common/logo-238479029-1681492343-1a7bfbbe807402a2c472c0ab13882f851681492343-480-0.png?0" class="logo">
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <a href="https://brindisespumante.com.ar/account/login/" class="modal-btn">
          <p id="non-serif">Inicia Sesión</p>
          <i class="fa-solid fa-caret-right"></i>
        </a>
        <a href="https://brindisespumante.com.ar/account/register/" class="modal-btn">
          <p id="non-serif">Registrarte en Brindis</p>
          <i class="fa-solid fa-caret-right"></i>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/pages/politica_de_cambio.html+phone.erb
<div class="politica-mobile">
  <div class="politica-text">
    <p id="non-serif">
      Si no estás conforme con nuestro producto,
      puedes realizar un cambio del mismo de alguna de las siguientes formas
    </p>
    <p id="non-serif">
      Ponte en contacto a
      <br>
      <strong>
        <%= link_to "mailto:brindiespumante@gmail.com", target: "_blank" do %>
          brindisespumante@gmail.com
        <% end %>
      </strong>
    </p>
    <p id="non-serif">
      Podrás cambiar el producto por otro del mismo valor. En caso de querer cambiarlo,
      deberás acercarte a nuestro local en Colegiales. Nosotras nos hacemos cargo de situaciones
      donde el producto llegue con algún error.
    </p>
    <p id="non-serif">
      Los cambios solo pueden ser realizados durante los 30 días siguientes a la compra para
      evitar que te cobremos el pedido de cambio
    </p>
    <p id="non-serif">
      <strong>No tenemos devolución</strong>
    </p>
  </div>
  <div class="politica-img-container">
    <%= image_tag "politica/plant-garbage.png", id: "politica-img" %>
  </div>
</div>

app/views/pages/politica_de_cambio.html.erb
<div class="container politica-de-cambio">
  <p id="non-serif">Si no estás conforme con nuestro producto, puedes realizar un cambio del mismo de alguna de las siguientes formas:</p>

  <p id="non-serif">
    Ponte en contacto a
    <br>
    <strong class="text-decoration-underline">
      <%= link_to "mailto:brindiespumante@gmail.com", target: "_blank" do %>
        brindiespumante@gmail.com
      <% end %>
    </strong>
  </p>

  <p id="non-serif">
    Podrás cambiar el producto por otro del mismo valor.
    <br>
    En caso de querer cambiarlo, deberás acercarte a nuestro local en Colegiales. Nosotros nos hacemos cargo en situaciones donde el producto llegue con algún error.
  </p>

  <p id="non-serif"Los cambios solo pueden ser realizadas durante los 30 días siguientes a la compra para evitar que te cobremos el pedido de cambio.</p>

  <p id="non-serif"><strong>No tenemos devolución.</strong></p>

  <div class="politica-images">
    <%= image_tag "Icono_Planta.png" %>
    <%= image_tag "inicio/basura.png" %>
  </div>
</div>

app/views/pages/product.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Serif:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

<div class="product-page">
  <div class="product-left">
    <div class="prod-info d-flex justify-content-between align-items-center">
      <ul style="margin-bottom: 0;">
        <li><h5 style="font-size: 1rem;">Product name</h5></li>
      </ul>

      <h5 style="font-size: 1rem;">Product price</h5>
    </div>
    <img src="https://d3ugyf2ht6aenh.cloudfront.net/stores/001/206/817/products/campera-saya1-516f16b12d47476b1a16815065696588-640-0.webp" style=" object-fit: cover;
    width: 35vw;
    height: 80vh;">
  </div>

  <div class="product-right" style="display: flex; flex-direction: column; justify-content: center;">
    <%# tamaño y cantidad %>
    <div style="border-bottom: 1.5px solid black; padding-bottom: 3vh;">
      <div class="d-flex" style="width: 50%;">
        <div class="d-flex" style="width: 50%;">
          <p><strong>Talle</strong></p>
          <%# size dropdown %>
          <input>
        </div>

        <div class="d-flex" style="width: 50%;">
          <p><strong>Cantidad</strong></p>
          <%# quantity dropdown %>
          <input>
        </div>
      </div>
    </div>

    <%# cuotas + descuento %>
    <div class="d-flex align-items-center" style="border-bottom: 1.5px solid black; padding: 1vh 0;">
      <img src="http://www.brindisespumante.com/assets/Icono_Planta-7514376d136212f58a0f4761124fe767235e7d30954d0505692a45c8fa933f49.png" style="height: 12vh;">

      <div style="width: 100%; margin-left: 10px;">
        <div class="d-flex justify-content-between" style="width: 100%; box-shadow: 0px 0px 5px rgba(0,0,0,0.5); border-radius: 5px; padding: 5px;">
          <p style="margin-bottom: 0;">3 cuotas sin interes</p>
          <div>
            <%# card icons %>
            <p style="margin-bottom: 0;">icons</p>
          </div>
        </div>
        <p style="margin-bottom: 0; margin-top: 8px;"><strong>10% de descuento</strong></p>
      </div>
    </div>

    <%# info %>
    <div style="padding: 3vh 0; border-bottom: 1.5px solid black;">
      <p>Info</p>
    </div>

    <%# envio %>
    <div style="display: grid; grid-template-columns: 3fr 2fr; padding: 3vh 0; border-bottom: 1.5px solid black;">
      <div>
        <p>"Envío brindis"</p>
        <p>Caba: $600</p>
        <p>Vicente Lopez, Martinez, San Isidro: $1000</p>
        <p>Victoria, San Fernando, Tigre, Don Torcuato, Garin, Benavidez: $1000</p>
        <p>Pilar, Escobar, Quilmes, Lomas de Zamora, Banfield, Temperley: $1500</p>
      </div>

      <div class="d-flex">
        <img src="https://i.ibb.co/LS1VsjB/envios.png" style="height: 5vh; margin-right: 1vw;">

        <div>
          <p><strong>Envio Gratis</strong></p>
          <p>Domicilio Céspedes 3146 piso 1 , Colegiales - Atención de Lun. a Vie. de 13 a 18 con previo aviso</p>
        </div>
      </div>
    </div>

    <%# añadir %>
    <%# btn here %>
  </div>
</div>

app/views/pages/quienes_somos.html+phone.erb
<div class="quienes-somos-mobile">
<div class="quienes-somos-text">
  <p id="non-serif">Somos tres hermanas creando un proyecto de indumentaria. Buscamos ofrecer <strong>comodidad y estética</strong>
  a través de un proceso de <strong>moda lenta.</strong> Queremos generar una producción <strong>consciente,</strong>
  y a la vez <strong>original.</strong> Esta nos involucra en el armado de prendas de principio a fin; en su diseño, corte,
  teñido, estampado, confección y packaging.</p>
  <p id="non-serif">
  Nos encontramos creando nuevas ideas, disfrutando del proceso e involucrando a nuestrxs clientes para alcanzar productos
  bellos y únicos.
  </p>
  <p id="non-serif">
  Esperamos que les guste :)
  </p>
</div>
  <div class="quienes-bottom">
  </div>
</div>

app/views/pages/quienes_somos.html.erb
<div class="quienes-somos">

  <div class="d-flex align-items-end">
    <%= image_tag "quienes_somos/quienes_somos_left.png" %>
  </div>

  <div class="quienes-somos-right">
    <div>
      <p id="non-serif">Somos tres hermanas creando un proyecto de indumentaria. Buscamos ofrecer <strong>comodidad y estética</strong> a través de un proceso de <strong>moda lenta.</strong> Queremos generar una producción <strong>consciente</strong>, y a la vez <strong>original.</strong> Esta nos involucra en el armado de las prendas de principio a fin; en su diseño, corte, teñido, estampado, confección, packaging.</p>
      <p id="non-serif">Nos encontramos creando nuevas ideas, disfrutando del proceso, e involucrando a nuestrxs clientes para alcanzar productos bellos y únicos.</p>
      <p id="non-serif">
        <strong>Esperamos que les guste :)</strong>
      </p>
    </div>
  </div>
</div>

app/views/pages/showroom.html+phone.erb
<div class="showroom_mobile">
  <div class="showroom_mobile_top">
    <div class="showroom_message">
     <p class="inside-text" id="non-serif"><em>Cualquier consulta no dudes en mandarnos un mensaje :)</em></p>
    </div>
    <div class="showroom_contact">
      <div style="padding: 0 1rem;">
        <div class="d-flex align-items-center" style="text-decoration: underline;"><%= image_tag "logo_wpp.png", id: "wpp-logo-showroom" %><p style="margin-left: 0.6rem;" id="non-serif">5491130824325</p></div>
        <p style="text-decoration: underline;" id="non-serif"><%= image_tag "icono_mail.png", id: "mail-logo" %>brindisespumante@gmail.com</p>
        <div class="d-flex"><%= image_tag "icono_location.png", id: "location-logo" %><p style="margin-left: 0.75rem;" id="non-serif">Cespedes 3146, entre Conde y Cap.Gral. Ramón Freire<p></div>
      </div>
      <div class="subtitle">
        <%= image_tag "showroom/linea.png", id: "linea" %>
        <h3 id="sub-showroom"><em id="non-serif" style="font-weight: normal;">SHOWROOM</em></h3>
      </div>
    </div>
  </div>
  <div class="showroom_mobile_bottom">
    <div class="bottom-text">
      <strong><p class="inside-text" id="non-serif">Showroom abierto Martes y Miercoles de <em style="font-weight: bolder;">14 a 18hs</em>
      <br>Disponibilidad para retirar Lunes a Viernes de <em style="font-weight: bolder;">14 a 18hs</em></p></strong>
    </div>
  </div>
</div>

app/views/pages/showroom.html.erb
<div class="showroom">
  <%= image_tag "showroom/showroom_pagina.png" %>

  <div class="showroom-right">
    <p id="non-serif">Nuestro Showroom se encuentra en Colegiales. No solo vendemos ropa, sino que también usamos el espacio para dar talleres, hacer eventos y generar encuentros culturales donde todxs se sientan bienvenidxs</p>

    <div>
      <p>
        <%= image_tag "logo_wpp.png", class: "icon" %>
        <%= link_to "https://wa.me/5491130824325?text=Hola", target: "_blank" do %>
          <strong id="non-serif">5491130824325</strong>
        <% end %>
      </p>
      <p>
        <%= image_tag "icono_mail.png", class: "icon" %>
        <%= link_to "mailto:brindiespumante@gmail.com", target: "_blank" do %>
          <strong id="non-serif">brindiespumante@gmail.com</strong>
        <% end %>
      </p>
      <p style="margin-bottom: -0.5rem;">
        <%= image_tag "icono_location.png", class: "icon" %>
        <strong id="non-serif">Cespedes 3146, entre Conde y Cap.Gral.Ramon Freire</strong>
      </p>
      <%= image_tag "showroom/linea.png", class: "linea" %>
    </div>

    <div data-controller="toggle">
      <p id="non-serif" class="shadow-left" data-action="click->toggle#toggle" style="cursor: pointer; text-align: center;">
        <strong>Showroom abierto Martes y Miercoles de 14 a 18hs con disponibilidad para retirar de Lunes a Viernes de 14 a 18hs</strong>
        <br>Cualquier consulta no dudes en mandarnos un mensaje :)
      </p>

      <div class="showroom-grid" style="align-items: flex-start;">
        <div data-toggle-target="placeholder" class="placeholder-showroom"></div>
        <div class="shadow-center d-none">
          Déjanos tu mensaje a que hora querés pasar y en el caso de retiro, también tu numero de pedido. 
          <br>
          Gracias!
        </div>

        <%= form_for [@contact], html: {class: "contact-form mt-0 d-none", data: {toggle_target: "element"}} do |form| %>
          <% if @contact.errors.any? %>
            <div id="error_explanation" class="bg-rose-200 pt-3 pb-1 mb-4 px-4 rounded-md">
              <div class="font-bold text-rose-700 text-sm pb-4"><%= pluralize(@contact.errors.count, "error") %> prohibited this page from being saved:</div>

              <ul class="pb-0 mb-0">
                <% @contact.errors.each do |error| %>
                  <li class="text-rose-600 pl-4 text-sm"><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <%= form.hidden_field :source, value: "showroom" %>

          <div class="d-flex flex-column">
            <p>Dejanos tu mensaje a que hora queres pasar y en el caso de retiro, tambien tu numero de pedido. Gracias!</p>
            <%= form.label :email, class: "text-sm" %>
            <%= form.text_field :email %>
          </div>

          <div class="d-flex">
            <div class="d-flex flex-column" style="width: 50%; padding-right: 1rem;">
              <%= form.label "Nº de pedido", class: "text-sm" %>
              <%= form.text_field :order_number %>
            </div>

            <div class="d-flex flex-column">
              <%= form.label :horario, class: "text-sm" %>
              <%= form.time_field :time, value: "%H:%M" %>
            </div>
          </div>

          <div class="d-flex flex-column">
            <%= form.label :content, class: "text-sm" %>
            <%= form.text_area :content %>
          </div>

          <div class= "d-none">
            <%= form.label :nickname %>
            <%= form.text_field :nickname, :hint => 'Leave this field blank!' %>
          </div>

          <%= form.submit "Enviar", class: "button-white", style: "font-size: 0.75rem; font-weight: bold;" %>

        <% end %>

        <%= image_tag "showroom.png" %>
      </div>
  </div>
</div>

app/views/pages/talleres.html.erb
<div class="talleres">
  <%= image_tag "talleres/entrada_byn.png" %>

  <div class="talleres-right" data-controller="galleria">
    <% if @talleres.empty? %>
      <h5>Aún no hay talleres. Vuelve pronto! :)</h5>
    <% else %>
      <section class="slider">
        <button class="slider__control prev"></button>
        <button class="slider__control next"></button>
        <div class="slider__container" data-multislide="true" data-step="4">
          <% @talleres.each do |taller|  %>
            <div class="slider__item">
              <div>
                <%= cl_image_tag taller.photo.key %>
                <p><%= taller.name.upcase %></p>
                <div class="line-clamp">
                  <%= taller.description %>
                </div>
              </div>
              <%= link_to "Mas info", workshop_path(taller), id: "non-serif", class: "mt-2", style: "text-decoration: underline;" %>
            </div>
          <% end %>
        </div>
      </section>
    <% end %>
  </div>
</div>

app/views/pages/tienda.html+phone.erb
<div class="tienda-mobile-top">
  <a href="https://www.brindisespumante.com.ar/productos/" id="non-serif" class="tienda-btn text-center" style="width: 38vw;">Todos los productos</a>
</div>

<div class="tienda-mobile-grid">
    <a href="https://www.brindisespumante.com.ar/pantalon/">
      <%= image_tag "dibujos_guia_de_talles/png/pantalones_baggy_2.png" %>
      <div class="tienda-btn-mobile">
        <p id="non-serif" >Pantalones</p>
        <i class="fa-solid fa-caret-right"></i>
      </div>
    </a>

    <a href="https://www.brindisespumante.com.ar/camperas-puffer/">
      <%= image_tag "dibujos_guia_de_talles/psd_tere/medidas_puffer_copy.png" %>
      <div class="tienda-btn-mobile">
        <p id="non-serif" >Camperas Puffer</p>
        <i class="fa-solid fa-caret-right"></i>
      </div>
    </a>

    <a href="https://www.brindisespumante.com.ar/buzos/">
      <%= image_tag "dibujos_guia_de_talles/png/talle_buzos.png" %>
      <div class="tienda-btn-mobile">
        <p id="non-serif" >Buzos</p>
        <i class="fa-solid fa-caret-right"></i>
      </div>
    </a>

    <a href="https://brindisespumante.com.ar/poleras-y-musculosas">
      <%= image_tag "dibujos_guia_de_talles/svg/talle_musculosas.svg" %>
      <div class="tienda-btn-mobile">
        <p id="non-serif">Poleras y Musculosas</p>
        <i class="fa-solid fa-caret-right"></i>
      </div>
    </a>

    <a href="https://www.brindisespumante.com.ar/camisas/">
      <%= image_tag "dibujos_guia_de_talles/png/talle_camisas.png" %>
      <div class="tienda-btn-mobile">
        <p id="non-serif" >Camisas</p>
        <i class="fa-solid fa-caret-right"></i>
      </div>
    </a>

    <a href="https://www.brindisespumante.com.ar/camperas/">
      <%= image_tag "dibujos_guia_de_talles/png/camperas.png" %>
      <div class="tienda-btn-mobile">
        <p id="non-serif" >Camperas</p>
        <i class="fa-solid fa-caret-right"></i>
      </div>
    </a>

    <a href="https://www.brindisespumante.com.ar/remeras/">
      <%= image_tag "dibujos_guia_de_talles/svg/talle_remerones.svg" %>
      <div class="tienda-btn-mobile">
        <p id="non-serif" >Remeras</p>
        <i class="fa-solid fa-caret-right"></i>
      </div>
    </a>

    <a href="https://www.brindisespumante.com.ar/bikinis/">
      <%= image_tag "dibujos_guia_de_talles/png/talle_bikini.png" %>
      <div class="tienda-btn-mobile">
        <p id="non-serif" >Bikinis</p>
        <i class="fa-solid fa-caret-right"></i>
      </div>
    </a>

    <a href="https://www.brindisespumante.com.ar/polleras/">
      <%= image_tag "pollera.png" %>
      <div class="tienda-btn-mobile">
        <p id="non-serif">Polleras</p>
        <i class="fa-solid fa-caret-right"></i>
      </div>
    </a>
</div>