config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/showroom", to: "pages#showroom"
  get "/quienes_somos", to: "pages#quienes_somos"
  get "/politica_de_cambio", to: "pages#politica_de_cambio"
  get "/talleres", to: "pages#talleres"
  get "/eventos", to: "pages#eventos"
  get "/tienda", to: "pages#tienda"
  get "/dashboard", to: "pages#dashboard"
  get "/product", to: "pages#product"

  resources :workshops, only: [:new, :create, :show, :destroy]
  resources :contacts, only: [:create]
  resources :events, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :items, only: [:new, :create, :destroy]
  resources :billboards, only: [:new, :create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :photo
  validates :link, format: { with: /https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)/, message: "URL no valido" }

  POSITIONS = ["Nube izquierda", "Nube central", "Nube derecha"]
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
    authorize @item

    @items = policy_scope(Item)
  end

  def create
    @previous_item = Item.find_by(position: params[:item][:position])
    @previous_item.destroy if @previous_item
    @item = Item.new(item_params)
    authorize @item

    if @item.save
      redirect_to new_item_path, notice: "Cambio exitoso!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:id])
    authorize @item

    if @item.destroy
      redirect_to new_item_path
    else
      render :new
    end
  end

  private

  def item_params
    params.require(:item).permit(:link, :position, :photo)
  end
end

app/views/items/new.html.erb
<%= simple_form_for @item, html: {class: "new-form", style: "margin-left: auto; margin-right: auto;"} do |f| %>
  <h5>Nubes</h5>
  <%= f.input :link, label: "URL de producto" %>
  <%= f.input :position, collection: Item::POSITIONS, label: "Posición" %>
  <%= f.input :photo, as: :file, label: "Imagen" %>
  <%= f.submit "Cambiar item" %>
<% end %>


<% unless @items.empty? %>
  <ul style="width: 45vw; margin-left: auto; margin-right: auto; margin-top: 5vh;">
    <h5>Borrar elementos:</h5>
    <% @items.each do |item| %>
      <%= link_to "Borrar elemento de #{item.position}", item_path(item), data: {turbo_method: :delete} %>
    <% end %>
  </ul>
<% end %>